### ISSUE TITLE
ImportError: No module named data.testing_data

### ISSUE THREAD

**Issue by BasharAG** [famavott/osint-scraper#122]
I keep getting this error when I try to deploy the page to localhost (last step in your instructions. Any ideas?

**Comment by gabrielx52** [comment]
You might also have to  pip install -r requirements.txt before the pserve
The data.teststin_data is in the repo so I'm not sure why you'd get that error.

**Comment by BasharAG** [comment]
Already ran it (tried both pip and pip3). No luck.

**Comment by 1N3** [comment]
Getting the same error:

pserve development.ini --reload                                                                                                                                                                   1 ↵ ──(Wed,Jan31)─┘
Starting monitor for PID 28172.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hupper/ipc.py", line 322, in spawn_main
    func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hupper/worker.py", line 237, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/pentest/recon/osint-scraper/osint_scraper/__init__.py", line 14, in main
    config.scan()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/__init__.py", line 1043, in scan
    ignore=ignore)
  File "/usr/local/lib/python2.7/dist-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/pentest/recon/osint-scraper/osint_scraper/scripts/dummy_recon.py", line 2, in <module>
    from ..data.testing_data import dumb_data
ImportError: No module named data.testing_data
Server with PID 28172 exited with code 1.
Waiting for changes before reloading.

**Comment by 1N3** [comment]
when I ran pip install -r requirements.txt, I get this error:
```
Collecting ipython==6.2.1 (from -r requirements.txt (line 24))
  Could not find a version that satisfies the requirement ipython==6.2.1 (from -r requirements.txt (line 24)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0)
No matching distribution found for ipython==6.2.1 (from -r requirements.txt (line 24))
```

**Comment by gabrielx52** [comment]
What version of python are you using?

**Comment by 1N3** [comment]
Python 2.7.14+

**Comment by 1N3** [comment]
oh, nvm... got it working by running python3 runapp.py.

**Comment by gabrielx52** [comment]
That may be the issue. It's written for 3.5+
