### ISSUE TITLE
ImportError: No module named pytest

### ISSUE THREAD

**Issue by ZerooCool** [famavott/osint-scraper#158]
pserve development.ini --reload

https://pastebin.com/dwdDWFMy

ImportError: No module named pytest
Server with PID 7721 exited with code 1.
Waiting for changes before reloading.

**Comment by gabrielx52** [comment]
You are using the wrong version of Python. V3.5+ is required.

**Comment by ZerooCool** [comment]
How i can add it and use it ?
( If you can explain )

**Comment by gabrielx52** [comment]
https://www.python.org/downloads/

You can download it from here.

**Comment by ZerooCool** [comment]
Python3 from debian stretch : 

apt-get install python3
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
python3 is already the newest version (3.5.3-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.



osint-scraper# pserve development.ini --reload
Starting monitor for PID 2717.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hupper/ipc.py", line 322, in spawn_main
    func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hupper/worker.py", line 237, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/zencool/osint-scraper/osint_scraper/__init__.py", line 14, in main
    config.scan()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/__init__.py", line 1043, in scan
    ignore=ignore)
  File "/usr/local/lib/python2.7/dist-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/home/zencool/osint-scraper/osint_scraper/conftest.py", line 6, in <module>
    import pytest
ImportError: No module named pytest
Server with PID 2717 exited with code 1.
Waiting for changes before reloading.

**Comment by ZerooCool** [comment]
Python3 from debian stretch : 

apt-get install python3
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
python3 is already the newest version (3.5.3-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.



osint-scraper# pserve development.ini --reload
Starting monitor for PID 2717.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hupper/ipc.py", line 322, in spawn_main
    func(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hupper/worker.py", line 237, in worker_main
    func(*spec_args, **spec_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/usr/local/lib/python2.7/dist-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/zencool/osint-scraper/osint_scraper/__init__.py", line 14, in main
    config.scan()
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/__init__.py", line 1043, in scan
    ignore=ignore)
  File "/usr/local/lib/python2.7/dist-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/home/zencool/osint-scraper/osint_scraper/conftest.py", line 6, in <module>
    import pytest
ImportError: No module named pytest
Server with PID 2717 exited with code 1.
Waiting for changes before reloading.

**Comment by ZerooCool** [comment]
apt-cache policy python3
python3:
  Installé : 3.5.3-1
  Candidat : 3.5.3-1
 Table de version :
 *** 3.5.3-1 500
        500 http://deb.debian.org/debian stable/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by gabrielx52** [comment]
Are you creating a virtual environment in python3 and activating it before you install the requirements?

**Comment by ZerooCool** [comment]
No ?
I use Debian Stretch 9 with virtualbox, and, want learn how i can use your script.

I need a virtual environnement python3 ?
I need install requirements ?

**Comment by gabrielx52** [comment]
I'm not familiar with that. 
These are the series of commands to get it work on most machines
After you complete these point your browser at http://localhost:6543/


`python3 -m venv ENV`
`source ENV/bin/activate`
`pip install -r requirements.txt `
`pip install -e .`
`pserve development.ini`

**Comment by ZerooCool** [comment]
Thank you, let's go, i test your command line. I can use your script ! <3
Like that !

**First**
python3 -m venv ENV
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
Failing command: ['/home/zencool/osint-scraper/ENV/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

**Ok - Then, i install**
apt-get install python3-venv

**Next**
python3 -m venv ENV
source ENV/bin/activate
pip install -r requirements.txt
pip install -e .
pserve development.ini

**The last line in the terminal**
Starting server in PID 2408.
Serving on http://localhost:6543
Serving on http://localhost:6543

**Resolved**
Firefox and use this URL : http://localhost:6543
